apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ml-prediction-dev
  namespace: argocd

spec:

  project: default

  source:

    repoURL: https://github.com/k8-consultant/ml-prediction-gitops.git

    targetRevision: main

    path: environments/dev


  destination:

    server: https://kubernetes.default.svc

    namespace: ml-dev


  syncPolicy:

    automated:

      prune: true

      selfHeal: true
