
apiVersion: v1
kind: Service

metadata:
  name: ml-prediction-api

spec:

  selector:
    app: ml-prediction-api

  ports:

    - protocol: TCP
      port: 80
      targetPort: 8000

  type: ClusterIP